# Uncomment the next line to define a global platform for your project
# platform :ios, '13.5'

target 'YahooApiApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YahooApiApp


pod 'Alamofire', '~> 5.2'
pod 'SwiftyJSON'
pod 'AlamofireImage'

end
